---
title: "Tarea 7"
output: html_notebook
---

Un ejemplo más complejo. Utiliza los siguientes datos, y agrega
si es necesario variables derivadas $a_3, a_4$ en la capa oculta.

```{r, message = FALSE}
library(tidyverse)
library(keras)
use_session_with_seed(123)

h <- function(x){
    exp(x)/(1 + exp(x))
}
x <- seq(-2,2,0.05)
p <- h(3 + x- 3 * x ^ 2 + 3 * cos(4 * x))
set.seed(280572)
x.2 <- runif(3000, -2, 2)
g.2 <- rbinom(3000, 1, h(3 + x.2 - 3 * x.2 ^ 2 + 3 * cos(4 * x.2)))
datos <- data.frame(x.2,g.2)
dat.p <- data.frame(x,p)
g <- qplot(x,p, geom='line', col='red')
g + geom_jitter(data = datos, aes(x=x.2,y=g.2), col ='black',
  position =position_jitter(height=0.05), alpha=0.4)
```

```{r}
ejemplo_mod <- keras_model_sequential()
ejemplo_mod %>% 
   layer_dense(units = 12, 
    activation = "sigmoid", kernel_regularizer = regularizer_l2(0.00001)) %>% 
  layer_dense(units = 1, 
    activation = "sigmoid", kernel_regularizer = regularizer_l2(0.00001) )
```

```{r}
x_mat <- as.matrix(datos$x.2, ncol = 1)
y <- datos$g.2
ejemplo_mod %>% compile(loss = "binary_crossentropy", 
  optimizer = optimizer_sgd(lr = 0.3, momentum = 0.9, nesterov = TRUE))
historia <- ejemplo_mod %>% 
  fit(x_mat, y, 
      batch_size = 100, epochs = 800, verbose = 0)
```

Después de verificar convergencia (chécalo examinando la variable
*historia*):

```{r}
plot(historia)
```


graficamos para ver que obtuvimos resultados similares:

```{r}
p_3 <- predict(ejemplo_mod, as.matrix(x, ncol = 1))
dat_3 <- tibble(x = x, p_2 = p_3)
ggplot(dat_3, aes(x = x, y = p_2)) + geom_line() +
geom_line(data = dat.p, aes(x = x, y = p), col='red') + ylim(c(0,1)) +
   geom_point(data = datos, aes(x = x.2, y = g.2))
```
