--- 
title: "Aprendizaje de máquina"
author: "Felipe González"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
bibliography: [referencias/book.bib]
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: felipegonzalez/aprendizaje-maquina-mcd
description: "Notas y material para el curso de aprendizaje de máquina (ITAM, 2019)"
---


# Temario y referencias {-}

**Todas las notas y material del curso estarán en este** [repositorio](https://github.com/felipegonzalez/aprendizaje-maquina-mcd-2019).

- Introducción al aprendizaje máquina
- Regresión lineal múltiple y descenso en gradiente
- Problemas de clasificación y regresión logística
- Validación cruzada y métodos de remuestreo
- Regularización y selección de modelos
- Redes neuronales
- Diagnóstico y mejora en problemas de aprendizaje supervisado.
- Árboles y bosques aleatorios
- Componentes principales y análisis de conglomerados

### Evaluación {-}

- Tareas semanales (25%)
- Examen parcial (30% práctico, 20% teórico)
- Un examen final (25% práctico)

### Referencias principales {-}

- [An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/), @ISL 
- [Curso de Machine Learning de Andrew Ng](https://www.coursera.org/learn/machine-learning), @Ngcoursera
- [Deep Learning](https://www.deeplearningbook.org/), @Goodfellow-et-al-2016

### Otras referencias {-}

- [Pattern Recognition and Machine Learning](http://www.springer.com/us/book/9780387310732), @Bishop
- [The Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/), @ESL

### Software: R y Rstudio {-}

- [R](https://cran.r-project.org) Sitio de R (CRAN)
- [Rstudio](https://www.rstudio.com/products/RStudio/) Interfaz gráfica para trabajar en R.
- [Recursos para aprender R](https://www.rstudio.com/online-learning/#R)

